# Libraries
library(tidyverse)
library(graphicsutils)
library(magrittr)
library(latex2exp)


# Functions
# source('./Functions/defaultParameters.R')
# source('./Functions/equilibrium.R')
# source('./Functions/disturbance.R')
# source('./Functions/disturbBoxplot.R')
# source('./Functions/stability.R')
source('./Functions/simAnnealing.R')
source('./Functions/tritrophic.R')
source('./Functions/omnivory.R')
source('./Functions/apparent.R')
source('./Functions/exploitative.R')
source('./Functions/partial.R')
source('./Functions/disconnected.R')
source('./Functions/parameterSpace.R')
source('./Functions/univariateDisturbance.R')
source('./Functions/multivariateDisturbance.R')
source('./Functions/multivariateDistFix.R')
source('./Functions/additivity.R')
source('./Functions/plotMotifs.R')
